### ISSUE TITLE
Compile?

### ISSUE THREAD

**Issue by jvijay-work** [photonlines/Go-Web-Server#1]
How to compile this code into a single binary?

**Comment by photonlines** [comment]
To generate the executable, you cd into the src directory and type 'go build -o server.exe main.go' which produces the server.exe executable that you can run.

If I'm misunderstanding your question, I think the links / examples below may help:

https://medium.com/@shijuvar/using-binary-only-packages-in-go-667bd7b123c8
https://github.com/YongHaoWu/goHike

**Comment by photonlines** [comment]
Issue closed
